### ISSUE TITLE
nsig function ending did not work

### ISSUE THREAD

**Issue by Wyrrrd** [iv-org/inv_sig_helper#45]
Go back to start, do not collect $200...

Similar to #41 from yesterday, but today.

```
[2024-12-17T18:49:46Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-17T18:49:47Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/03dbdfab/player_ias.vflset/en_US/base.js
[2024-12-17T18:49:47Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
```

**Comment by unixfox** [comment]
Hello,

Your issue has already been reported. Duplicate of https://github.com/iv-org/inv_sig_helper/issues/44

**Comment by Wyrrrd** [comment]
Well, #43's error message is nowhere to be found in my logs...

**Comment by rockerBOO** [comment]
This is a new error. Different from yesterday. Just started occuring 30 minutes ago.

**Comment by ExZylan** [comment]
+1. Same problem here

**Comment by rockerBOO** [comment]
#47 should now fix this issue

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I just pulled the latest image from ~30 minutes ago, still seeing the same error.

```
[2024-12-17T21:12:21Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/03dbdfab/player_ias.vflset/en_US/base.js

[2024-12-17T21:12:21Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
```

**Comment by rockerBOO** [comment]
It might have been building still so just make sure it's updated.

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I'm not sure how to verify it has the latest change, but this is the output of my docker pull so I'm pretty sure everything is up to date.

```
docker pull quay.io/invidious/inv-sig-helper:latest   
latest: Pulling from invidious/inv-sig-helper
Digest: sha256:fca9bd68e69bc782aaf2be0ef8b3dc7a160dd57b2ac219a1caf16a33c249264c
Status: Image is up to date for quay.io/invidious/inv-sig-helper:latest
quay.io/invidious/inv-sig-helper:latest
```

**Comment by rockerBOO** [comment]
I can confirm thats the latest for me as well. How are you restarting your containers? It has been working for me so just considering outliers
